### ISSUE TITLE
Fonts (css/fonts.css) is not being included in libraries yaml file

### ISSUE THREAD

**Issue by anairamzap-mobomo** [zivtech/bear_skin#13]
Hi, I think I found a bug: 
In the libraries file (_docroot_/themes/bear_skin/bear_skin.libraries.yml) there is a css file for the fonts included, but its filename is "web-fonts.css" and I think this should be "**fonts.css**" to grab the google fonts generated by gulp using fonts.list file, or at least that seems to be the current filename.

> bear_skin.libraries.yml

<pre><code>
global-styles:
  version: 1.x
  css:
    theme:
      css/web-fonts.css: <b><-- here</b>
        minified: true
      css/bear_skin.css:
        minified: false
        ...
</pre></code>

Let me know if I'm correct,
Thanks!
m

**Comment by jkaeser** [comment]
Wow, sorry we took so long getting back to you about this @anairamzap-mobomo. Thanks for catching this and letting us know! This is indeed a bug, and I committed 279111993d071cb13f279e8c5b2f19becfe94c11 to fix it.
