### ISSUE TITLE
bear_skin.libraries.yml has a non-breaking space in it

### ISSUE THREAD

**Issue by BrianWalters** [zivtech/bear_skin#14]
Ran into this issue because my Drupal 8 install couldn't parse the yaml file.

There's a space after `version:` in `global-styles` that is not a normal space character.

You can see in https://github.com/zivtech/bear_skin/blob/8.x-2.x/bear_skin.libraries.yml that the syntax highlighting is borked on that line. The property appears blue when it should be green.

Hope this helps.

**Comment by jodyHamilton** [comment]
Thank you, I edited it
