### ISSUE TITLE
Theme path is not properly called by Drupal

### ISSUE THREAD

**Issue by johnreytanquinco** [zivtech/bear_skin#16]
We have a running site and use this as base theme to develop our custom theme.
I was able to enable and apply the them but accessing the pattern-lab link `/themes/custom/bear_skin/pattern-lab/public/` gives be broken pages. I am getting `404's` in all files. See inspected element error below:
```
styleguide.html?1505447967165:25 GET http://localhost:8080/components/styleguide/custom-styleguide-specific.css 
styleguide.html?1505447967165:29 GET http://localhost:8080/components/vendor/bower/raw/flexboxgrid/dist/flexboxgrid.css 
styleguide.html?1505447967165:30 GET http://localhost:8080/css/bear_skin.css 
styleguide.html?1505447967165:5595 GET http://localhost:8080/components/styleguide/js/domready.js 
styleguide.html?1505447967165:5596 GET http://localhost:8080/components/styleguide/js/drupal.js 
styleguide.html?1505447967165:5594 GET http://localhost:8080/components/styleguide/js/styleguide.js 
styleguide.html?1505447967165:5593 GET http://localhost:8080/components/vendor/bower/js/jquery.js 
styleguide.html?1505447967165:5603 GET http://localhost:8080/js/scripts.js 
styleguide.html?1505447967165:5597 GET http://localhost:8080/components/styleguide/js/jquery.once.js 
styleguide.html?1505447967165:5594 GET http://localhost:8080/components/styleguide/js/styleguide.js 
styleguide.html?1505447967165:5595 GET http://localhost:8080/components/styleguide/js/domready.js 
styleguide.html?1505447967165:5596 GET http://localhost:8080/components/styleguide/js/drupal.js 
styleguide.html?1505447967165:5597 GET http://localhost:8080/components/styleguide/js/jquery.once.js 
styleguide.html?1505447967165:5603 
```

Of course when, I modify the path, say, `href="/css/bear_skin.css"` to `href="/themes/custom/bear_skin/css/bear_skin.css"` that would fix the error. But I dont want to put changes in all `.html` files the theme has.

**Comment by jkaeser** [comment]
@johnreytanquinco The paths to these files are built with one of our Gulp tasks in mind (see https://github.com/zivtech/bear_skin/blob/8.x-2.x/gulp-tasks/patternLab.js). If you install the Gulp dependencies and run `gulp watch`, Pattern Lab will open up at `localhost:3003` (tunable in your [gulpfile.yml](https://github.com/zivtech/bear_skin/blob/8.x-2.x/default.gulpfile.yml#L75)), and everything will load fine.

If you prefer to access via the path you mentioned, you can tweak the two files in the `bear_skin/_meta` directory. Add the theme path to any line asking for a CSS or JavaScript file.

For example, in `_00-head.twig`:
```
<link rel="stylesheet" href="/components/styleguide/custom-styleguide-specific.css">
```
becomes
```
<link rel="stylesheet" href="/themes/custom/bear_skin/components/styleguide/custom-styleguide-specific.css">
```

Once you regenerate Pattern Lab, all your files will load.
